/*
 * WiiMedic - report.c
 * Generates a comprehensive diagnostic report and saves to SD card
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <malloc.h>
#include <time.h>
#include <gccore.h>
#include <fat.h>
#include <ogc/lwp_watchdog.h>

#include "report.h"
#include "ui_common.h"
#include "system_info.h"
#include "nand_health.h"
#include "ios_check.h"
#include "storage_test.h"
#include "controller_test.h"
#include "network_test.h"

#define REPORT_MAX_SIZE  32768
#define REPORT_PATH      "sd:/WiiMedic_Report.txt"

/*---------------------------------------------------------------------------*/
void run_report_generator(void) {
    char *report;
    int pos = 0;
    char section[8192];
    char buf[128];
    FILE *fp;

    ui_draw_info("This will run ALL diagnostic modules and save results.");
    {
        char pathm[128];
        snprintf(pathm, sizeof(pathm), "Report will be saved to: %s", REPORT_PATH);
        ui_draw_info(pathm);
    }
    printf("\n");

    report = (char*)malloc(REPORT_MAX_SIZE);
    if (!report) {
        ui_draw_err("Memory allocation failed");
        return;
    }
    memset(report, 0, REPORT_MAX_SIZE);

    /* Header */
    pos += snprintf(report + pos, REPORT_MAX_SIZE - pos,
        "==========================================================\n"
        "     WiiMedic Diagnostic Report v" WIIMEDIC_VERSION "\n"
        "==========================================================\n\n"
        "Generated by WiiMedic - Wii System Diagnostic & Health Monitor\n"
        "Share this report when asking for help on forums or Reddit.\n"
        "----------------------------------------------------------\n\n");

    /* 1: System Info */
    printf(UI_BCYAN "   [1/6]" UI_WHITE " Collecting system information...\n" UI_RESET);
    memset(section, 0, sizeof(section));
    get_system_info_report(section, sizeof(section));
    pos += snprintf(report + pos, REPORT_MAX_SIZE - pos, "%s", section);
    ui_draw_ok("Done.");

    /* 2: NAND Health */
    printf(UI_BCYAN "   [2/6]" UI_WHITE " Scanning NAND health...\n" UI_RESET);
    {
        s32 isfs_ret = ISFS_Initialize();
        if (isfs_ret >= 0) {
            u32 used_bytes = 0, used_inodes = 0;
            ISFS_GetUsage("/", &used_bytes, &used_inodes);
            ISFS_Deinitialize();
        }
    }
    memset(section, 0, sizeof(section));
    get_nand_health_report(section, sizeof(section));
    pos += snprintf(report + pos, REPORT_MAX_SIZE - pos, "%s", section);
    ui_draw_ok("Done.");

    /* 3: IOS Check */
    printf(UI_BCYAN "   [3/6]" UI_WHITE " Scanning IOS installations...\n" UI_RESET);
    {
        u32 title_count = 0;
        ES_GetNumTitles(&title_count);
        if (title_count > 0) {
            u64 *tlist = (u64*)memalign(32, title_count * sizeof(u64));
            if (tlist) {
                ES_GetTitles(tlist, title_count);
                free(tlist);
            }
        }
    }
    memset(section, 0, sizeof(section));
    get_ios_check_report(section, sizeof(section));
    if (strlen(section) > 0) {
        pos += snprintf(report + pos, REPORT_MAX_SIZE - pos, "%s", section);
    } else {
        pos += snprintf(report + pos, REPORT_MAX_SIZE - pos,
            "=== IOS INSTALLATION SCAN ===\n"
            "Run IOS Scan from main menu first to populate this section.\n\n");
    }
    ui_draw_ok("Done.");

    /* 4: Storage */
    printf(UI_BCYAN "   [4/6]" UI_WHITE " Checking storage devices...\n" UI_RESET);
    memset(section, 0, sizeof(section));
    get_storage_test_report(section, sizeof(section));
    if (strlen(section) > 0) {
        pos += snprintf(report + pos, REPORT_MAX_SIZE - pos, "%s", section);
    } else {
        pos += snprintf(report + pos, REPORT_MAX_SIZE - pos,
            "=== STORAGE TEST ===\n"
            "Run Storage Test from main menu first to populate this section.\n\n");
    }
    ui_draw_ok("Done.");

    /* 5: Controllers */
    printf(UI_BCYAN "   [5/6]" UI_WHITE " Checking controllers...\n" UI_RESET);
    memset(section, 0, sizeof(section));
    get_controller_test_report(section, sizeof(section));
    pos += snprintf(report + pos, REPORT_MAX_SIZE - pos, "%s", section);
    ui_draw_ok("Done.");

    /* 6: Network */
    printf(UI_BCYAN "   [6/6]" UI_WHITE " Checking network...\n" UI_RESET);
    memset(section, 0, sizeof(section));
    get_network_test_report(section, sizeof(section));
    if (strlen(section) > 0) {
        pos += snprintf(report + pos, REPORT_MAX_SIZE - pos, "%s", section);
    } else {
        pos += snprintf(report + pos, REPORT_MAX_SIZE - pos,
            "=== NETWORK TEST ===\n"
            "Run Network Test from main menu first to populate this section.\n\n");
    }
    ui_draw_ok("Done.");

    /* Footer */
    pos += snprintf(report + pos, REPORT_MAX_SIZE - pos,
        "----------------------------------------------------------\n"
        "END OF WIIMEDIC DIAGNOSTIC REPORT\n"
        "For best results, run each module from the main menu first,\n"
        "then generate this report to capture all data.\n"
        "----------------------------------------------------------\n");

    /* Save to SD */
    printf("\n");
    ui_draw_info("Saving report to SD card...");

    fp = fopen(REPORT_PATH, "w");
    if (fp) {
        fwrite(report, 1, strlen(report), fp);
        fclose(fp);
        ui_draw_ok("Report saved successfully!");

        snprintf(buf, sizeof(buf), "File: %s", REPORT_PATH);
        ui_draw_ok(buf);

        snprintf(buf, sizeof(buf), "Size: %d bytes", (int)strlen(report));
        ui_draw_ok(buf);

        printf("\n");
        ui_draw_info("You can now share this file when asking for help.");
        ui_draw_info("Copy WiiMedic_Report.txt from your SD card to your PC.");
    } else {
        ui_draw_err("Failed to save report!");
        ui_draw_warn("Make sure an SD card is inserted and writable.");
        ui_draw_info("Try reformatting the SD card as FAT32.");
    }

    free(report);
}
